# ~/.config/starship.toml

# GLOBAL SETTINGS
format = """
$os$username$hostname$shlvl$directory$git_branch$git_status$docker_context$python$nodejs$rust$golang$cmd_duration$status
$character"""

add_newline = false

# PROMPT CHARACTER
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[V](bold yellow)"

# OS MODULE (for Kali-style awareness)
[os]
format = "[$symbol]($style) "
style = "bold white"
disabled = false

[os.symbols]
Linux = "🐧"
Windows = ""
Macos = ""
Kali = ""  # Tux or custom symbol

# USERNAME MODULE
[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style) "

# HOSTNAME MODULE
[hostname]
ssh_only = false
format = "[@$hostname](bold black) "
disabled = false

# SHLVL (show if in nested shells)
[shlvl]
threshold = 2
format = "⇵ [$shlvl](bold red) "
disabled = false

# DIRECTORY MODULE
[directory]
style = "bold blue"
read_only = " "
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
home_symbol = "~"

# GIT BRANCH MODULE
[git_branch]
symbol = " "
style = "bold purple"

# GIT STATUS MODULE
[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style) )'
conflicted = "⚔️ "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "✓"
untracked = "🛈${count}"
stashed = "📦"
modified = "✎${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

# DOCKER CONTEXT MODULE
[docker_context]
symbol = "🐳 "
format = "[$symbol$context](blue) "
only_with_files = true
disabled = false

# PYTHON MODULE
[python]
symbol = " "
style = "bold yellow"
format = '[${symbol}${version}]($style) '

# NODEJS MODULE
[nodejs]
symbol = " "
style = "bold green"
format = '[${symbol}${version}]($style) '

# GO MODULE
[golang]
symbol = " "
style = "bold cyan"
format = '[${symbol}${version}]($style) '

# RUST MODULE
[rust]
symbol = "🦀 "
style = "bold red"
format = '[${symbol}${version}]($style) '

# COMMAND DURATION
[cmd_duration]
min_time = 500
format = "⏱️ [$duration]($style) "
style = "yellow"

# EXIT STATUS MODULE
[status]
style = "bold red"
symbol = "✖"
format = "[$symbol $status]($style) "
disabled = false

# TIME MODULE
[time]
disabled = false
format = "🕒 [$time]($style) "
time_format = "%R"
style = "bold white"

# DISABLE UNUSED MODULES
[battery]
disabled = true

[memory_usage]
disabled = true
