choco upgrade fastfetch -y
choco upgrade firefox -y
choco upgrade flow-launcher -y
choco upgrade micro -y
choco upgrade nodejs -y 
choco upgrade python -y 
choco upgrade ruby -y
choco upgrade starship -y
choco upgrade vscode -y