choco upgrade discord -y
choco upgrade ditto -y
choco upgrade fastfetch -y
choco upgrade firefox -y
choco upgrade flow-launcher -y
choco upgrade googledrive -y
choco upgrade micro -y
choco upgrade nodejs -y 
choco upgrade obs-studio -y
choco upgrade python -y 
choco upgrade ruby -y
choco upgrade starship -y
choco upgrade vivaldi -y 
choco upgrade vlc -y
choco upgrade vscode -y
choco upgrade windirstat -y